project:
  type: default
  output-dir: ../docs
  render:
    - index.qmd

format:
  revealjs:
    output-ext: "slides.html"
    search: false
    theme: [serif, ../stage/custom.scss]
    controls: true
    controls-tutorial: true
    navigation-mode: linear
    embedded: true
    logo: unsw-logo.png
    transition: fade
    transition-speed: slow
    slide-number: c/t
    preview-links: false
    margin: 0
    width: 3072
    height: 1845
    min-scale: 1
    max-scale: 1
    history: false
    code-annotations: none
    include-before-body: ../stage/deck-stage-open.html
    include-after-body:
      - ../stage/reveal-fixes.html
      - ../stage/deck-stage-close.html

html-math-method: katex
